version: '3.9'

services:
  api:
    image: otanazarov/turk-tili-api:latest
    container_name: turk-tili-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  user:
    image: otanazarov/turk-tili-user:latest
    container_name: turk-tili-user
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

  admin:
    image: otanazarov/turk-tili-admin:latest
    container_name: turk-tili-admin
    ports:
      - "3001:80"
    depends_on:
      - api
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turk_tili_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
