version: '3.9'

services:
  backend:
    image: otanazarov/turk-tili-api:latest
    container_name: turk-tili-api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - redis  # Redis'ga ham depend qo'shing
    networks:
      - app-network

  admin:
    image: otanazarov/turk-tili-admin:latest
    container_name: turk-tili-admin
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  user:
    image: otanazarov/turk-tili-user:latest
    container_name: turk-tili-user
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: turk-tili-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turk_tili
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge