version: '3.9'

services:
  backend:
    image: otanazarov/turk-tili-api:latest
    container_name: turk-tili-api
    restart: always
    env_file:
    - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  admin:
    image: otanazarov/turk-tili-admin:latest
    container_name: turk-tili-admin
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

  user:
    image: otanazarov/turk-tili-user:latest
    container_name: turk-tili-user
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: turk-tili-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turk_tili
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
